[menu]
executable = 'rofi'
args = [
    '-dmenu',
    '-markup-rows',
    '-p={prompt}',
]

[format]
window_format = '{app_name}: {urgency_start}<i>“{title}”</i>{urgency_end} — on workspace {workspace_name}   <span alpha="20000">({id})</span>'
workspace_format = '<b>Workspace {name}</b>   <span alpha="20000">({id})</span>'
html_escape = true
urgency_start = '<span background="darkred" foreground="yellow">'
urgency_end = '</span>'
