[cursor]
style = "Beam"

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font"

# Color Schemes:  --------------------------------------------------------------

# Gruvbox Light
[colors.bright]
black = "0x928374"
blue = "0x076678"
cyan = "0x427b58"
green = "0x79740e"
magenta = "0x8f3f71"
red = "0x9d0006"
white = "0x3c3836"
yellow = "0xb57614"

[colors.normal]
black = "0xfbf1c7"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0x7c6f64"
yellow = "0xd79921"

[colors.primary]
background = "0xfbf1c7"
foreground = "0x3c3836"

# # TokyoNight Day
# # Default colors
# [colors.primary]
# background = '#e1e2e7'
# foreground = '#3760bf'
#
# #[colors.cursor]
# #cursor = '#3760bf'
# #text = '#e1e2e7'
#
# # Normal colors
# [colors.normal]
# black = '#b4b5b9'
# red = '#f52a65'
# green = '#587539'
# yellow = '#8c6c3e'
# blue = '#2e7de9'
# magenta = '#9854f1'
# cyan = '#007197'
# white = '#6172b0'
#
# # Bright colors
# [colors.bright]
# black = '#a1a6c5'
# red = '#ff4774'
# green = '#5c8524'
# yellow = '#a27629'
# blue = '#358aff'
# magenta = '#a463ff'
# cyan = '#007ea8'
# white = '#3760bf'
#
# # Indexed Colors
# [[colors.indexed_colors]]
# index = 16
# color = '#b15c00'
#
# [[colors.indexed_colors]]
# index = 17
# color = '#c64343'

# # Gruvbox Dark
# [colors.bright]
# black =   "0x928374"
# red =     "0xfb4934"
# green =   "0xb8bb26"
# yellow =  "0xfabd2f"
# blue =    "0x83a598"
# magenta = "0xd3869b"
# cyan =    "0x8ec07c"
# white =   "0xebdbb2"
#
# [colors.normal]
# black =   "0x282828"
# red =     "0xcc241d"
# green =   "0x98971a"
# yellow =  "0xd79921"
# blue =    "0x458588"
# magenta = "0xb16286"
# cyan =    "0x689d6a"
# white =   "0xa89984"
#
# [colors.primary]
# background = "0x282828"
# foreground = "0xebdbb2"
